export const SITE_CONFIG = {
    name: "Cyclone Suite",
    description: "Open-source React components with stunning animations - Inspired by the best in modern UI design",
    url: "https://cyclonesuite.dev",
    github: "https://github.com/cyclonesuite",
    twitter: "https://twitter.com/cyclonesuite",
};

// Navigation structure with all components from multiple sources
export const NAVIGATION = {
    getStarted: [
        { name: "Installation", slug: "/docs", description: "Get started with Cyclone Suite" },
    ],
    // BLOCKS - From ShadcnBlocks
    blocks: [
        { name: "Hero Sections", slug: "/docs/blocks/hero", description: "High-impact hero sections", isNew: true },
        { name: "Feature Sections", slug: "/docs/blocks/features", description: "Showcase your features" },

        { name: "Testimonials", slug: "/docs/blocks/testimonials", description: "Social proof sections" },
        { name: "FAQ Sections", slug: "/docs/blocks/faq", description: "Accordion FAQs" },
        { name: "Footer", slug: "/docs/blocks/footer", description: "Page footers" },
        { name: "Navbar", slug: "/docs/blocks/navbar", description: "Navigation headers" },
        { name: "CTA Sections", slug: "/docs/blocks/cta", description: "Call to action blocks" },
        { name: "Contact Forms", slug: "/docs/blocks/contact", description: "Contact sections" },
        { name: "Blog Layouts", slug: "/docs/blocks/blog", description: "Blog grids and posts" },
        { name: "Bento Grid", slug: "/docs/blocks/bento", description: "Bento-style layouts" },
        { name: "Stats Section", slug: "/docs/blocks/stats", description: "Statistics displays" },
    ],
    // MOTION EFFECTS - From Motion Primitives  
    motion: [
        { name: "Text Effect", slug: "/docs/components/text-effect", description: "Animated text transitions", isNew: true },
        { name: "Text Morph", slug: "/docs/components/text-morph", description: "Morph between strings" },
        { name: "Text Scramble", slug: "/docs/components/text-scramble", description: "Scrambling reveal effect" },
        { name: "Border Trail", slug: "/docs/components/border-trail", description: "Animated border effect" },
        { name: "Glow Effect", slug: "/docs/components/glow-effect", description: "Dynamic glow on hover" },
        { name: "Spotlight", slug: "/docs/components/spotlight", description: "Cursor spotlight" },
        { name: "Magnetic", slug: "/docs/components/magnetic", description: "Magnetic cursor attraction" },
        { name: "Tilt Card", slug: "/docs/components/tilt-card", description: "3D tilt on hover" },
        { name: "Infinite Slider", slug: "/docs/components/infinite-slider", description: "Endless carousel" },
        { name: "Dock", slug: "/docs/components/dock", description: "macOS dock magnification" },
        { name: "Morphing Dialog", slug: "/docs/components/morphing-dialog", description: "Transform origin modal" },
        { name: "Scroll Progress", slug: "/docs/components/scroll-progress", description: "Reading progress bar" },
        { name: "Wobble Card", slug: "/docs/components/wobble-card", description: "Mouse wobble effect", isNew: true },
        { name: "Draggable Card", slug: "/docs/components/draggable-card", description: "Drag with tilt", isNew: true },
        { name: "Direction Aware", slug: "/docs/components/direction-aware-hover", description: "Entry direction" },
        { name: "Following Pointer", slug: "/docs/components/following-pointer", description: "Custom cursor" },
    ],
    // VISUAL EFFECTS - From Aceternity
    effects: [
        { name: "Aurora Background", slug: "/docs/components/aurora-background", description: "Northern lights effect", isNew: true },
        { name: "Background Beams", slug: "/docs/components/background-beams", description: "Energy beam lines" },
        { name: "Meteor Shower", slug: "/docs/components/meteor-shower", description: "Falling meteors" },
        { name: "Sparkles", slug: "/docs/components/sparkles", description: "Particle sparkles" },
        { name: "Vortex Background", slug: "/docs/components/vortex", description: "Swirling vortex" },
        { name: "Wavy Background", slug: "/docs/components/wavy-background", description: "Wave animations" },
        { name: "Grid Background", slug: "/docs/components/grid-background", description: "Animated grids" },
        { name: "Lamp Effect", slug: "/docs/components/lamp-effect", description: "Light cone effect" },
        { name: "Hero Parallax", slug: "/docs/components/hero-parallax", description: "Scroll parallax" },
        { name: "Tracing Beam", slug: "/docs/components/tracing-beam", description: "SVG path tracer" },
        { name: "Moving Border", slug: "/docs/components/moving-border", description: "Animated border" },
        { name: "Noise Background", slug: "/docs/components/noise-background", description: "Gradient + noise", isNew: true },
        { name: "Background Gradient", slug: "/docs/components/background-gradient-anim", description: "Moving blobs" },
        { name: "Background Lines", slug: "/docs/components/background-lines", description: "Wave SVG paths" },
        { name: "Shooting Stars", slug: "/docs/components/shooting-stars", description: "Starfield effect" },
        { name: "Background Ripple", slug: "/docs/components/background-ripple", description: "Grid ripple" },
        { name: "Background Boxes", slug: "/docs/components/background-boxes", description: "Color boxes" },
        { name: "Glare Card", slug: "/docs/components/glare-card", description: "Linear glare", isNew: true },
        { name: "Card Spotlight", slug: "/docs/components/card-spotlight", description: "Mouse spotlight" },
        { name: "Glowing Effect", slug: "/docs/components/glowing-effect", description: "Conic glow" },
        { name: "Canvas Reveal", slug: "/docs/components/canvas-reveal", description: "Dot expand" },
        { name: "SVG Mask Effect", slug: "/docs/components/svg-mask-effect", description: "Cursor mask" },
        { name: "Hero Highlight", slug: "/docs/components/hero-highlight", description: "Text highlight" },
        { name: "Evervault Card", slug: "/docs/components/evervault-card", description: "Encrypted hover" },
        { name: "Glowing Stars", slug: "/docs/components/glowing-stars", description: "Star particles" },
        { name: "Hover Border", slug: "/docs/components/hover-border-gradient", description: "Gradient border" },
    ],
    // CARDS & COMPONENTS - Mixed sources
    components: [
        { name: "Loader", slug: "/docs/components/loader", description: "Loading spinner" },
        { name: "3D Card", slug: "/docs/components/3d-card", description: "Perspective tilt card" },
        { name: "Expandable Card", slug: "/docs/components/expandable-card", description: "Click to expand" },
        { name: "Card Stack", slug: "/docs/components/card-stack", description: "Stacked testimonials" },
        { name: "Focus Cards", slug: "/docs/components/focus-cards", description: "Blur unfocused" },
        { name: "File Upload", slug: "/docs/components/file-upload", description: "Drag drop upload" },
        { name: "Image Compare", slug: "/docs/components/image-compare", description: "Before/after slider" },
        { name: "Carousel", slug: "/docs/components/carousel", description: "Smooth carousel" },
        { name: "3D Marquee", slug: "/docs/components/3d-marquee", description: "Perspective scroll" },
        { name: "Timeline", slug: "/docs/components/timeline", description: "Scroll timeline" },
        { name: "World Map", slug: "/docs/components/world-map", description: "Interactive globe" },
        { name: "Dynamic Island", slug: "/docs/components/dynamic-island", description: "Apple-style island" },
        { name: "Tooltip Card", slug: "/docs/components/tooltip-card", description: "Rich tooltip" },
        { name: "Container Scroll", slug: "/docs/components/container-scroll", description: "3D perspective" },
        { name: "Layout Grid", slug: "/docs/components/layout-grid", description: "Animated grid" },
        { name: "Animated Tooltip", slug: "/docs/components/animated-tooltip", description: "Avatar tooltip" },
        { name: "Infinite Cards", slug: "/docs/components/infinite-moving-cards", description: "Scrolling cards" },
        { name: "Floating Navbar", slug: "/docs/components/floating-navbar", description: "Hide/show nav" },
        { name: "Multi-Step Loader", slug: "/docs/components/multi-step-loader", description: "Step loading" },
        { name: "Sticky Banner", slug: "/docs/components/sticky-banner", description: "Dismissable top" },
        { name: "3D Pin", slug: "/docs/components/three-d-pin", description: "Animated pin" },
        { name: "Lens", slug: "/docs/components/lens", description: "Zoom magnifier" },
        { name: "Signup Form", slug: "/docs/components/signup-form", description: "Animated form" },
    ],
    // TEXT ANIMATIONS
    texts: [
        { name: "Typewriter", slug: "/docs/components/typewriter", description: "Typing animation" },
        { name: "Glitch Text", slug: "/docs/components/glitch-text", description: "Glitch distortion" },
        { name: "Matrix Text", slug: "/docs/components/matrix-text", description: "Matrix rain" },
        { name: "Shimmer Text", slug: "/docs/components/shimmer-text", description: "Shine effect" },
        { name: "Flip Words", slug: "/docs/components/flip-words", description: "Word rotation" },
        { name: "Text Generate", slug: "/docs/components/text-generate", description: "Fade in words" },
        { name: "Encrypted Text", slug: "/docs/components/encrypted-text", description: "Decrypt reveal" },
        { name: "Gradient Heading", slug: "/docs/components/gradient-heading", description: "Gradient text" },
        { name: "Spinning Text", slug: "/docs/components/spinning-text", description: "Circular rotation" },
        { name: "Text Hover Effect", slug: "/docs/components/text-hover-effect", description: "Gradient on hover" },
        { name: "Colourful Text", slug: "/docs/components/colourful-text", description: "Multi-color chars" },
    ],
    // BUTTONS
    buttons: [
        { name: "Particle Button", slug: "/docs/components/particle-button", description: "Click particles" },
        { name: "Gradient Button", slug: "/docs/components/gradient-button", description: "Gradient animations" },
        { name: "Magnetic Button", slug: "/docs/components/magnetic-button", description: "Cursor attraction" },
        { name: "Shimmer Button", slug: "/docs/components/shimmer-button", description: "Shine sweep" },
        { name: "Moving Border Button", slug: "/docs/components/moving-border-button", description: "Animated border" },
        { name: "Stateful Button", slug: "/docs/components/stateful-button", description: "State transitions" },
        { name: "Neumorph Button", slug: "/docs/components/neumorph-button", description: "Soft UI style" },
    ],
    // INTERACTIVE - Cult UI & others
    interactive: [
        { name: "Color Picker", slug: "/docs/components/color-picker", description: "Color selection" },
        { name: "Sortable List", slug: "/docs/components/sortable-list", description: "Drag reorder" },
        { name: "Code Block", slug: "/docs/components/code-block", description: "Syntax highlight" },
        { name: "Toolbar Dynamic", slug: "/docs/components/toolbar-dynamic", description: "Morphing toolbar" },
        { name: "Resizable Navbar", slug: "/docs/components/resizable-navbar", description: "Scroll-aware nav" },
        { name: "Accordion", slug: "/docs/components/accordion", description: "Animated accordion" },
        { name: "Animated Modal", slug: "/docs/components/animated-modal", description: "Smooth dialog" },
        { name: "Animated Tabs", slug: "/docs/components/animated-tabs", description: "Layout tabs" },
        { name: "Vanish Input", slug: "/docs/components/vanish-input", description: "Vanishing input" },
    ],
    // PRIMITIVES - From Base UI
    primitives: [
        { name: "Toast", slug: "/docs/components/toast", description: "Notifications", isNew: true },
        { name: "Tooltip", slug: "/docs/components/tooltip", description: "Hover tips" },
        { name: "Popover", slug: "/docs/components/popover", description: "Float panel" },
        { name: "Switch", slug: "/docs/components/switch", description: "Toggle switch" },
        { name: "Select", slug: "/docs/components/select", description: "Dropdown" },
        { name: "Progress", slug: "/docs/components/progress", description: "Progress bars" },
        { name: "Slider", slug: "/docs/components/slider", description: "Range slider" },
        { name: "Avatar", slug: "/docs/components/avatar", description: "User avatar" },
        { name: "Dialog", slug: "/docs/components/dialog", description: "Modal dialog" },
        { name: "Alert Dialog", slug: "/docs/components/alert-dialog", description: "Confirm modal" },
        { name: "Context Menu", slug: "/docs/components/context-menu", description: "Right-click" },
        { name: "Checkbox", slug: "/docs/components/checkbox", description: "Animated check" },
        { name: "Radio", slug: "/docs/components/radio", description: "Radio group" },
        { name: "Toggle", slug: "/docs/components/toggle", description: "Toggle group" },
        { name: "Input", slug: "/docs/components/input", description: "Text input" },
        { name: "Collapsible", slug: "/docs/components/collapsible", description: "Show/hide" },
        { name: "Separator", slug: "/docs/components/separator", description: "Divider" },
        { name: "Meter", slug: "/docs/components/meter", description: "Usage meter" },
        { name: "Preview Card", slug: "/docs/components/preview-card", description: "Link preview" },
    ],
    // AI COMPONENTS
    ai: [
        { name: "AI Input", slug: "/docs/components/ai-input", description: "Prompt interface" },
        { name: "AI Loading", slug: "/docs/components/ai-loading", description: "Processing states" },
    ],
    // SPECIAL EFFECTS - Aceternity
    special: [
        { name: "Macbook Scroll", slug: "/docs/components/macbook-scroll", description: "Hero cinematic" },
        { name: "Apple Cards", slug: "/docs/components/apple-cards", description: "Apple carousel" },
        { name: "GitHub Globe", slug: "/docs/components/github-globe", description: "3D Earth" },
        { name: "Sticky Scroll", slug: "/docs/components/sticky-scroll", description: "Section reveal" },
        { name: "Parallax Scroll", slug: "/docs/components/parallax-scroll", description: "Multi-speed scroll" },
        { name: "Link Preview", slug: "/docs/components/link-preview", description: "Hover preview" },
    ],
};

// Component data for all components
export const COMPONENT_DATA: Record<string, {
    title: string;
    description: string;
    package: string;
    category: string;
    isNew?: boolean;
    source?: string;
}> = {
    // Loaders & Basic
    "loader": {
        title: "Loader",
        description: "Elegant loading spinner with smooth animations",
        package: "@cyclonesuite/loader",
        category: "Components",
    },
    // Motion Effects
    "text-effect": {
        title: "Text Effect",
        description: "Animated text transitions with fade, slide, and scale",
        package: "@cyclonesuite/text-effect",
        category: "Motion",
        isNew: true,
        source: "motion-primitives",
    },
    "text-morph": {
        title: "Text Morph",
        description: "Smoothly transform characters between strings",
        package: "@cyclonesuite/text-morph",
        category: "Motion",
        source: "motion-primitives",
    },
    "text-scramble": {
        title: "Text Scramble",
        description: "Character-by-character scrambling reveal effect",
        package: "@cyclonesuite/text-scramble",
        category: "Motion",
        source: "motion-primitives",
    },
    "border-trail": {
        title: "Border Trail",
        description: "Animated trail following element border",
        package: "@cyclonesuite/border-trail",
        category: "Motion",
        source: "motion-primitives",
    },
    "glow-effect": {
        title: "Glow Effect",
        description: "Dynamic glowing highlight on hover and focus",
        package: "@cyclonesuite/glow-effect",
        category: "Motion",
        source: "motion-primitives",
    },
    "spotlight": {
        title: "Spotlight",
        description: "Focused flashlight effect following cursor",
        package: "@cyclonesuite/spotlight",
        category: "Motion",
        source: "motion-primitives",
    },
    "magnetic": {
        title: "Magnetic",
        description: "Elements attracted toward cursor position",
        package: "@cyclonesuite/magnetic",
        category: "Motion",
        source: "motion-primitives",
    },
    "tilt-card": {
        title: "Tilt Card",
        description: "3D parallax tilt reacting to mouse position",
        package: "@cyclonesuite/tilt-card",
        category: "Motion",
        source: "motion-primitives",
    },
    "infinite-slider": {
        title: "Infinite Slider",
        description: "Continuous looping carousel of items",
        package: "@cyclonesuite/infinite-slider",
        category: "Motion",
        source: "motion-primitives",
    },
    "dock": {
        title: "Dock",
        description: "macOS-style dock with magnification",
        package: "@cyclonesuite/dock",
        category: "Motion",
        source: "motion-primitives",
    },
    "morphing-dialog": {
        title: "Morphing Dialog",
        description: "Modal transforming from trigger element",
        package: "@cyclonesuite/morphing-dialog",
        category: "Motion",
        source: "motion-primitives",
    },
    "scroll-progress": {
        title: "Scroll Progress",
        description: "Visual indicator for page scroll position",
        package: "@cyclonesuite/scroll-progress",
        category: "Motion",
        source: "motion-primitives",
    },
    // Visual Effects
    "aurora-background": {
        title: "Aurora Background",
        description: "Subtle northern lights wave animation",
        package: "@cyclonesuite/aurora-background",
        category: "Effects",
        isNew: true,
        source: "aceternity",
    },
    "background-beams": {
        title: "Background Beams",
        description: "Energy beams flowing along SVG paths",
        package: "@cyclonesuite/background-beams",
        category: "Effects",
        source: "aceternity",
    },
    "meteor-shower": {
        title: "Meteor Shower",
        description: "Falling meteors or streaks of light",
        package: "@cyclonesuite/meteor-shower",
        category: "Effects",
        source: "aceternity",
    },
    "sparkles": {
        title: "Sparkles",
        description: "Configurable shimmering star particles",
        package: "@cyclonesuite/sparkles",
        category: "Effects",
        source: "aceternity",
    },
    "vortex": {
        title: "Vortex Background",
        description: "Swirling colorful vortex animation",
        package: "@cyclonesuite/vortex",
        category: "Effects",
        source: "aceternity",
    },
    "wavy-background": {
        title: "Wavy Background",
        description: "Smooth wave animation for sections",
        package: "@cyclonesuite/wavy-background",
        category: "Effects",
        source: "aceternity",
    },
    "grid-background": {
        title: "Grid Background",
        description: "Animated grid patterns",
        package: "@cyclonesuite/grid-background",
        category: "Effects",
        source: "aceternity",
    },
    "lamp-effect": {
        title: "Lamp Effect",
        description: "Dramatic top-down light cone",
        package: "@cyclonesuite/lamp-effect",
        category: "Effects",
        source: "aceternity",
    },
    "hero-parallax": {
        title: "Hero Parallax",
        description: "Complex scroll with rotation and opacity",
        package: "@cyclonesuite/hero-parallax",
        category: "Effects",
        source: "aceternity",
    },
    "tracing-beam": {
        title: "Tracing Beam",
        description: "Glowing beam following SVG path on scroll",
        package: "@cyclonesuite/tracing-beam",
        category: "Effects",
        source: "aceternity",
    },
    "moving-border": {
        title: "Moving Border",
        description: "Continuously animated perimeter",
        package: "@cyclonesuite/moving-border",
        category: "Effects",
        source: "aceternity",
    },
    // Cards
    "3d-card": {
        title: "3D Card",
        description: "Perspective tilt with elevated elements",
        package: "@cyclonesuite/3d-card",
        category: "Components",
        source: "aceternity",
    },
    "expandable-card": {
        title: "Expandable Card",
        description: "Click to expand full content",
        package: "@cyclonesuite/expandable-card",
        category: "Components",
        source: "aceternity",
    },
    "card-stack": {
        title: "Card Stack",
        description: "Cards cycling to back of deck",
        package: "@cyclonesuite/card-stack",
        category: "Components",
        source: "aceternity",
    },
    "focus-cards": {
        title: "Focus Cards",
        description: "Hover focuses one, blurs others",
        package: "@cyclonesuite/focus-cards",
        category: "Components",
        source: "aceternity",
    },
    "file-upload": {
        title: "File Upload",
        description: "Drag-drop upload with micro-animations",
        package: "@cyclonesuite/file-upload",
        category: "Components",
        source: "aceternity",
    },
    "image-compare": {
        title: "Image Compare",
        description: "Before/after slider comparison",
        package: "@cyclonesuite/image-compare",
        category: "Components",
        source: "motion-primitives",
    },
    "carousel": {
        title: "Carousel",
        description: "Fluid carousel with interactions",
        package: "@cyclonesuite/carousel",
        category: "Components",
        source: "aceternity",
    },
    "3d-marquee": {
        title: "3D Marquee",
        description: "Perspective scrolling marquee",
        package: "@cyclonesuite/3d-marquee",
        category: "Components",
        source: "aceternity",
    },
    "timeline": {
        title: "Timeline",
        description: "Vertical timeline with scroll beam",
        package: "@cyclonesuite/timeline",
        category: "Components",
        source: "aceternity",
    },
    "world-map": {
        title: "World Map",
        description: "Interactive globe with connections",
        package: "@cyclonesuite/world-map",
        category: "Components",
        source: "aceternity",
    },
    "dynamic-island": {
        title: "Dynamic Island",
        description: "Apple-inspired adaptive island",
        package: "@cyclonesuite/dynamic-island",
        category: "Components",
        source: "cult-ui",
    },
    // Text Animations
    "typewriter": {
        title: "Typewriter",
        description: "Classic typing animation",
        package: "@cyclonesuite/typewriter",
        category: "Texts",
    },
    "glitch-text": {
        title: "Glitch Text",
        description: "RGB split glitch distortion",
        package: "@cyclonesuite/glitch-text",
        category: "Texts",
    },
    "matrix-text": {
        title: "Matrix Text",
        description: "Falling matrix characters",
        package: "@cyclonesuite/matrix-text",
        category: "Texts",
    },
    "shimmer-text": {
        title: "Shimmer Text",
        description: "Gradient shimmer animation",
        package: "@cyclonesuite/shimmer-text",
        category: "Texts",
    },
    "flip-words": {
        title: "Flip Words",
        description: "Vertical word rotation",
        package: "@cyclonesuite/flip-words",
        category: "Texts",
        source: "aceternity",
    },
    "text-generate": {
        title: "Text Generate",
        description: "Fade-in word by word",
        package: "@cyclonesuite/text-generate",
        category: "Texts",
        source: "aceternity",
    },
    "encrypted-text": {
        title: "Encrypted Text",
        description: "Decrypt reveal animation",
        package: "@cyclonesuite/encrypted-text",
        category: "Texts",
        source: "aceternity",
    },
    "gradient-heading": {
        title: "Gradient Heading",
        description: "Multi-color gradient text",
        package: "@cyclonesuite/gradient-heading",
        category: "Texts",
        source: "cult-ui",
    },
    "spinning-text": {
        title: "Spinning Text",
        description: "Circular rotating text",
        package: "@cyclonesuite/spinning-text",
        category: "Texts",
        source: "motion-primitives",
    },
    // Buttons
    "particle-button": {
        title: "Particle Button",
        description: "Click-triggered particle explosion",
        package: "@cyclonesuite/particle-button",
        category: "Buttons",
    },
    "gradient-button": {
        title: "Gradient Button",
        description: "Animated gradient with hover shine",
        package: "@cyclonesuite/gradient-button",
        category: "Buttons",
    },
    "magnetic-button": {
        title: "Magnetic Button",
        description: "Cursor attraction effect",
        package: "@cyclonesuite/magnetic-button",
        category: "Buttons",
    },
    "shimmer-button": {
        title: "Shimmer Button",
        description: "Shine sweep on hover",
        package: "@cyclonesuite/shimmer-button",
        category: "Buttons",
    },
    "moving-border-button": {
        title: "Moving Border Button",
        description: "Animated border travel",
        package: "@cyclonesuite/moving-border-button",
        category: "Buttons",
    },
    "stateful-button": {
        title: "Stateful Button",
        description: "Idle/Loading/Success states",
        package: "@cyclonesuite/stateful-button",
        category: "Buttons",
        source: "aceternity",
    },
    "neumorph-button": {
        title: "Neumorph Button",
        description: "Soft UI neumorphic style",
        package: "@cyclonesuite/neumorph-button",
        category: "Buttons",
        source: "cult-ui",
    },
    // Interactive
    "color-picker": {
        title: "Color Picker",
        description: "Interactive color selection",
        package: "@cyclonesuite/color-picker",
        category: "Interactive",
        source: "cult-ui",
    },
    "sortable-list": {
        title: "Sortable List",
        description: "Drag-and-drop reordering",
        package: "@cyclonesuite/sortable-list",
        category: "Interactive",
        source: "cult-ui",
    },
    "code-block": {
        title: "Code Block",
        description: "Syntax highlighted code",
        package: "@cyclonesuite/code-block",
        category: "Interactive",
        source: "cult-ui",
    },
    "toolbar-dynamic": {
        title: "Toolbar Dynamic",
        description: "Morphing toolbar states",
        package: "@cyclonesuite/toolbar-dynamic",
        category: "Interactive",
        source: "motion-primitives",
    },
    "resizable-navbar": {
        title: "Resizable Navbar",
        description: "Scroll-aware navigation",
        package: "@cyclonesuite/resizable-navbar",
        category: "Interactive",
        source: "aceternity",
    },
    "accordion": {
        title: "Accordion",
        description: "Animated accordion panels",
        package: "@cyclonesuite/accordion",
        category: "Interactive",
        source: "motion-primitives",
    },
    "animated-modal": {
        title: "Animated Modal",
        description: "Smooth entry/exit dialog",
        package: "@cyclonesuite/animated-modal",
        category: "Interactive",
        source: "aceternity",
    },
    "animated-tabs": {
        title: "Animated Tabs",
        description: "Layout transition tabs",
        package: "@cyclonesuite/animated-tabs",
        category: "Interactive",
        source: "aceternity",
    },
    // AI Components
    "ai-input": {
        title: "AI Input",
        description: "AI prompt interface",
        package: "@cyclonesuite/ai-input",
        category: "AI",
    },
    "ai-loading": {
        title: "AI Loading",
        description: "Multi-step processing states",
        package: "@cyclonesuite/ai-loading",
        category: "AI",
    },
    // Special Effects
    "macbook-scroll": {
        title: "Macbook Scroll",
        description: "Cinematic hero scroll effect",
        package: "@cyclonesuite/macbook-scroll",
        category: "Special",
        source: "aceternity",
    },
    "apple-cards": {
        title: "Apple Cards",
        description: "Apple.com style carousel",
        package: "@cyclonesuite/apple-cards",
        category: "Special",
        source: "aceternity",
    },
    "github-globe": {
        title: "GitHub Globe",
        description: "Interactive 3D earth",
        package: "@cyclonesuite/github-globe",
        category: "Special",
        source: "aceternity",
    },
    "sticky-scroll": {
        title: "Sticky Scroll",
        description: "Section reveal on scroll",
        package: "@cyclonesuite/sticky-scroll",
        category: "Special",
        source: "aceternity",
    },
    "parallax-scroll": {
        title: "Parallax Scroll",
        description: "Multi-speed column scroll",
        package: "@cyclonesuite/parallax-scroll",
        category: "Special",
        source: "aceternity",
    },
    "link-preview": {
        title: "Link Preview",
        description: "Hover website preview",
        package: "@cyclonesuite/link-preview",
        category: "Special",
        source: "aceternity",
    },
    // NEW - Aceternity Visual Effects
    "glare-card": {
        title: "Glare Card",
        description: "Linear-style glare effect following mouse position",
        package: "@cyclonesuite/glare-card",
        category: "Effects",
        isNew: true,
        source: "aceternity",
    },
    "wobble-card": {
        title: "Wobble Card",
        description: "Translate and scale on mousemove with spring physics",
        package: "@cyclonesuite/wobble-card",
        category: "Motion",
        isNew: true,
        source: "aceternity",
    },
    "card-spotlight": {
        title: "Card Spotlight",
        description: "Radial gradient spotlight following cursor",
        package: "@cyclonesuite/card-spotlight",
        category: "Effects",
        source: "aceternity",
    },
    "svg-mask-effect": {
        title: "SVG Mask Effect",
        description: "Cursor-driven mask revealing hidden content",
        package: "@cyclonesuite/svg-mask-effect",
        category: "Effects",
        source: "aceternity",
    },
    "canvas-reveal": {
        title: "Canvas Reveal",
        description: "Dot grid that expands on hover (Clerk-style)",
        package: "@cyclonesuite/canvas-reveal",
        category: "Effects",
        source: "aceternity",
    },
    "glowing-effect": {
        title: "Glowing Effect",
        description: "Conic gradient border glow following mouse",
        package: "@cyclonesuite/glowing-effect",
        category: "Effects",
        source: "aceternity",
    },
    "hero-highlight": {
        title: "Hero Highlight",
        description: "Text highlight with animated background effect",
        package: "@cyclonesuite/hero-highlight",
        category: "Effects",
        source: "aceternity",
    },
    "noise-background": {
        title: "Noise Background",
        description: "Animated gradients with real-time noise overlay",
        package: "@cyclonesuite/noise-background",
        category: "Effects",
        isNew: true,
        source: "aceternity",
    },
    "background-gradient-anim": {
        title: "Background Gradient",
        description: "Smooth morphing gradient blobs",
        package: "@cyclonesuite/background-gradient-anim",
        category: "Effects",
        source: "aceternity",
    },
    "background-lines": {
        title: "Background Lines",
        description: "SVG wave paths animating in a pattern",
        package: "@cyclonesuite/background-lines",
        category: "Effects",
        source: "aceternity",
    },
    "shooting-stars": {
        title: "Shooting Stars",
        description: "Starry night sky with shooting stars",
        package: "@cyclonesuite/shooting-stars",
        category: "Effects",
        source: "aceternity",
    },
    "background-ripple": {
        title: "Background Ripple",
        description: "Grid cells that pulse and highlight on hover",
        package: "@cyclonesuite/background-ripple",
        category: "Effects",
        source: "aceternity",
    },
    "background-boxes": {
        title: "Background Boxes",
        description: "Grid boxes that light up in random colors",
        package: "@cyclonesuite/background-boxes",
        category: "Effects",
        source: "aceternity",
    },
    "evervault-card": {
        title: "Evervault Card",
        description: "Encrypted text background with gradient reveal",
        package: "@cyclonesuite/evervault-card",
        category: "Effects",
        source: "aceternity",
    },
    "glowing-stars": {
        title: "Glowing Stars",
        description: "Cards with animated glowing star particles",
        package: "@cyclonesuite/glowing-stars",
        category: "Effects",
        source: "aceternity",
    },
    "hover-border-gradient": {
        title: "Hover Border Gradient",
        description: "Rotating gradient border on hover",
        package: "@cyclonesuite/hover-border-gradient",
        category: "Effects",
        source: "aceternity",
    },
    // NEW - Aceternity Components
    "draggable-card": {
        title: "Draggable Card",
        description: "Tiltable, draggable cards with spring bounce",
        package: "@cyclonesuite/draggable-card",
        category: "Motion",
        isNew: true,
        source: "aceternity",
    },
    "direction-aware-hover": {
        title: "Direction Aware Hover",
        description: "Overlay enters from mouse entry direction",
        package: "@cyclonesuite/direction-aware-hover",
        category: "Motion",
        source: "aceternity",
    },
    "following-pointer": {
        title: "Following Pointer",
        description: "Custom animated cursor with trailing content",
        package: "@cyclonesuite/following-pointer",
        category: "Motion",
        source: "aceternity",
    },
    "text-hover-effect": {
        title: "Text Hover Effect",
        description: "Gradient outline following mouse over text",
        package: "@cyclonesuite/text-hover-effect",
        category: "Texts",
        source: "aceternity",
    },
    "colourful-text": {
        title: "Colourful Text",
        description: "Per-character color with hover scale animation",
        package: "@cyclonesuite/colourful-text",
        category: "Texts",
        source: "aceternity",
    },
    "tooltip-card": {
        title: "Tooltip Card",
        description: "Rich tooltip cards with preview content on hover",
        package: "@cyclonesuite/tooltip-card",
        category: "Components",
        source: "aceternity",
    },
    "container-scroll": {
        title: "Container Scroll",
        description: "3D perspective rotation into view",
        package: "@cyclonesuite/container-scroll",
        category: "Components",
        source: "aceternity",
    },
    "layout-grid": {
        title: "Layout Grid",
        description: "Animated grid items that expand on click",
        package: "@cyclonesuite/layout-grid",
        category: "Components",
        source: "aceternity",
    },
    "animated-tooltip": {
        title: "Animated Tooltip",
        description: "Avatar stack with hover tooltips",
        package: "@cyclonesuite/animated-tooltip",
        category: "Components",
        source: "aceternity",
    },
    "infinite-moving-cards": {
        title: "Infinite Moving Cards",
        description: "Continuously scrolling testimonial cards",
        package: "@cyclonesuite/infinite-moving-cards",
        category: "Components",
        source: "aceternity",
    },
    "floating-navbar": {
        title: "Floating Navbar",
        description: "Navbar that hides on scroll down, reveals on up",
        package: "@cyclonesuite/floating-navbar",
        category: "Components",
        source: "aceternity",
    },
    "multi-step-loader": {
        title: "Multi-Step Loader",
        description: "Sequential loading steps with progress",
        package: "@cyclonesuite/multi-step-loader",
        category: "Components",
        source: "aceternity",
    },
    "sticky-banner": {
        title: "Sticky Banner",
        description: "Dismissable sticky top banner",
        package: "@cyclonesuite/sticky-banner",
        category: "Components",
        source: "aceternity",
    },
    "three-d-pin": {
        title: "3D Pin",
        description: "Animated pins that elevate on hover",
        package: "@cyclonesuite/three-d-pin",
        category: "Components",
        source: "aceternity",
    },
    "lens": {
        title: "Lens",
        description: "Magnifying glass zoom following cursor",
        package: "@cyclonesuite/lens",
        category: "Components",
        source: "aceternity",
    },
    "signup-form": {
        title: "Signup Form",
        description: "Animated form with staggered fields",
        package: "@cyclonesuite/signup-form",
        category: "Components",
        source: "aceternity",
    },
    "vanish-input": {
        title: "Vanish Input",
        description: "Input with sliding placeholders and vanish effect",
        package: "@cyclonesuite/vanish-input",
        category: "Interactive",
        source: "aceternity",
    },
    // NEW - Base UI Primitives
    "toast": {
        title: "Toast",
        description: "Animated notification toasts with multiple variants",
        package: "@cyclonesuite/toast",
        category: "Primitives",
        isNew: true,
        source: "base-ui",
    },
    "tooltip": {
        title: "Tooltip",
        description: "Smooth hover tooltips with arrow pointer",
        package: "@cyclonesuite/tooltip",
        category: "Primitives",
        source: "base-ui",
    },
    "popover": {
        title: "Popover",
        description: "Floating content panel with settings",
        package: "@cyclonesuite/popover",
        category: "Primitives",
        source: "base-ui",
    },
    "switch": {
        title: "Switch",
        description: "Animated toggle switches with spring physics",
        package: "@cyclonesuite/switch",
        category: "Primitives",
        source: "base-ui",
    },
    "select": {
        title: "Select",
        description: "Animated dropdown select menu",
        package: "@cyclonesuite/select",
        category: "Primitives",
        source: "base-ui",
    },
    "progress": {
        title: "Progress",
        description: "Linear, striped, and circular progress indicators",
        package: "@cyclonesuite/progress",
        category: "Primitives",
        source: "base-ui",
    },
    "slider": {
        title: "Slider",
        description: "Interactive range slider with gradient fills",
        package: "@cyclonesuite/slider",
        category: "Primitives",
        source: "base-ui",
    },
    "avatar": {
        title: "Avatar",
        description: "User avatars with sizes, stacks, and status",
        package: "@cyclonesuite/avatar",
        category: "Primitives",
        source: "base-ui",
    },
    "dialog": {
        title: "Dialog",
        description: "Modal dialog with backdrop blur",
        package: "@cyclonesuite/dialog",
        category: "Primitives",
        source: "base-ui",
    },
    "alert-dialog": {
        title: "Alert Dialog",
        description: "Confirmation modal with destructive action",
        package: "@cyclonesuite/alert-dialog",
        category: "Primitives",
        source: "base-ui",
    },
    "context-menu": {
        title: "Context Menu",
        description: "Right-click context menu with icons",
        package: "@cyclonesuite/context-menu",
        category: "Primitives",
        source: "base-ui",
    },
    "checkbox": {
        title: "Checkbox",
        description: "Animated checkboxes with SVG path drawing",
        package: "@cyclonesuite/checkbox",
        category: "Primitives",
        source: "base-ui",
    },
    "radio": {
        title: "Radio",
        description: "Radio button group with card layout",
        package: "@cyclonesuite/radio",
        category: "Primitives",
        source: "base-ui",
    },
    "toggle": {
        title: "Toggle",
        description: "Multi-select toggle group buttons",
        package: "@cyclonesuite/toggle",
        category: "Primitives",
        source: "base-ui",
    },
    "input": {
        title: "Input",
        description: "Styled input variants with icon, error, and textarea",
        package: "@cyclonesuite/input",
        category: "Primitives",
        source: "base-ui",
    },
    "collapsible": {
        title: "Collapsible",
        description: "Animated show/hide panels with chevron",
        package: "@cyclonesuite/collapsible",
        category: "Primitives",
        source: "base-ui",
    },
    "separator": {
        title: "Separator",
        description: "Horizontal, gradient, and vertical dividers",
        package: "@cyclonesuite/separator",
        category: "Primitives",
        source: "base-ui",
    },
    "meter": {
        title: "Meter",
        description: "Animated usage meter bars with gradient fills",
        package: "@cyclonesuite/meter",
        category: "Primitives",
        source: "base-ui",
    },
    "preview-card": {
        title: "Preview Card",
        description: "Hover preview cards for links",
        package: "@cyclonesuite/preview-card",
        category: "Primitives",
        source: "base-ui",
    },
};

// Block data for all blocks
export const BLOCK_DATA: Record<string, {
    title: string;
    description: string;
    package: string;
    category: string;
    isNew?: boolean;
    variants?: number;
}> = {
    "hero": {
        title: "Hero Sections",
        description: "High-impact hero sections with stunning animations and modern layouts for your landing pages",
        package: "@cyclonesuite/hero",
        category: "Blocks",
        isNew: true,
        variants: 5,
    },
    "features": {
        title: "Feature Sections",
        description: "Showcase your product features with beautiful grid layouts and animated icons",
        package: "@cyclonesuite/features",
        category: "Blocks",
        variants: 4,
    },

    "testimonials": {
        title: "Testimonials",
        description: "Social proof sections with customer quotes, ratings, and profile cards",
        package: "@cyclonesuite/testimonials",
        category: "Blocks",
        variants: 4,
    },
    "faq": {
        title: "FAQ Sections",
        description: "Animated accordion FAQs with smooth expand/collapse transitions",
        package: "@cyclonesuite/faq",
        category: "Blocks",
        variants: 2,
    },
    "footer": {
        title: "Footer",
        description: "Modern page footers with navigation links, social icons, and newsletter signup",
        package: "@cyclonesuite/footer",
        category: "Blocks",
        variants: 3,
    },
    "navbar": {
        title: "Navbar",
        description: "Responsive navigation headers with dropdowns, mobile menus, and scroll effects",
        package: "@cyclonesuite/navbar",
        category: "Blocks",
        variants: 4,
    },
    "cta": {
        title: "CTA Sections",
        description: "Call-to-action blocks with gradient backgrounds and compelling copy",
        package: "@cyclonesuite/cta",
        category: "Blocks",
        variants: 3,
    },
    "contact": {
        title: "Contact Forms",
        description: "Contact sections with forms, maps, and contact information cards",
        package: "@cyclonesuite/contact",
        category: "Blocks",
        variants: 2,
    },
    "blog": {
        title: "Blog Layouts",
        description: "Blog grids and post layouts with featured images and metadata",
        package: "@cyclonesuite/blog",
        category: "Blocks",
        variants: 3,
    },
    "bento": {
        title: "Bento Grid",
        description: "Bento-style grid layouts inspired by Apple design language",
        package: "@cyclonesuite/bento",
        category: "Blocks",
        variants: 2,
    },
    "stats": {
        title: "Stats Section",
        description: "Statistics displays with animated counters and visual indicators",
        package: "@cyclonesuite/stats",
        category: "Blocks",
        variants: 3,
    },
};
